# Generated by Django 6.0.3 on 2026-04-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('opening_date', models.DateField(blank=True, db_column='beginning_date', null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PeriodScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scheme_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SEMIMONTHLY', 'Semi-Monthly'), ('NTH_WEEKDAY', 'Nth Weekday')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('weekly_interval', models.PositiveIntegerField(blank=True, help_text='Number of weeks between anchors (1 = weekly, 2 = biweekly, etc.)', null=True)),
                ('monthly_interval', models.PositiveIntegerField(blank=True, help_text='Number of months between periods (1 = monthly, 3 = quarterly, etc.)', null=True)),
                ('cut_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month where the split occurs (2–30)', null=True)),
                ('nth_weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True)),
                ('nth_ordinal', models.PositiveSmallIntegerField(blank=True, help_text='1=first, 2=second, 3=third, 4=fourth', null=True)),
                ('rules', models.JSONField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_path', models.TextField(unique=True)),
                ('level', models.IntegerField(db_column='depth')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='budget.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['full_path'],
            },
        ),
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imp', models.IntegerField(default=0)),
                ('hist', models.CharField(blank=True, max_length=50)),
                ('sort_key', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budget.category')),
            ],
            options={
                'ordering': ['date', 'category', 'sort_key'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seq', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budget.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budget.category')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('label', models.CharField(max_length=100)),
                ('sequence', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='budget.periodscheme')),
            ],
            options={
                'ordering': ['scheme', 'sequence'],
                'unique_together': {('scheme', 'sequence')},
            },
        ),
    ]
