# Generated by Django 6.0.3 on 2026-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('file_path', models.CharField(max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=20)),
                ('inserted', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('kept', models.IntegerField(default=0)),
                ('total_imported', models.IntegerField(default=0)),
                ('total_db', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
