# Generated by Django 6.0.3 on 2026-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_importlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Run Importer',
                'verbose_name_plural': 'Run Importer',
                'managed': False,
            },
        ),
    ]
