# Generated by Django 6.0.3 on 2026-06-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_importerentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imp', models.IntegerField(default=0)),
                ('hist', models.CharField(blank=True, max_length=50)),
                ('sort_key', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget', to='budget.category')),
            ],
            options={
                'ordering': ['date', 'category', 'sort_key'],
            },
        ),
        migrations.DeleteModel(
            name='Budgets',
        ),
    ]
