# Generated by Django 6.0.3 on 2026-06-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budget_delete_budgets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['date', 'category__full_path']},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='hist',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='imp',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='sort_key',
        ),
        migrations.AddField(
            model_name='budget',
            name='type',
            field=models.CharField(choices=[('planned', 'Planned'), ('transient', 'Transient')], default='transient', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budget.category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(),
        ),
    ]
