# Generated by Django 6.0.3 on 2026-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_delete_importlog_budget_seq_alter_budget_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='seq',
            field=models.IntegerField(default=0),
        ),
    ]
