# Generated by Django 6.0.3 on 2026-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_budget_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
