# Generated by Django 6.0.3 on 2026-06-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_alter_budget_created_at_alter_budget_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['date', 'category_id__full_path']},
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='account',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='category',
            new_name='category_id',
        ),
    ]
