# Generated by Django 6.0.3 on 2026-06-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_alter_budget_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['date', 'category__full_path']},
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='category_id',
            new_name='category',
        ),
    ]
