# Generated by Django 6.0.3 on 2026-07-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_alter_budget_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDashboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Budget Dashboard',
                'verbose_name_plural': 'Budget Dashboard',
                'managed': False,
            },
        ),
    ]
