# Generated by Django 6.0.3 on 2026-08-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_budgetdashboardentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('anchor_day', models.IntegerField(blank=True, null=True)),
                ('anchor_weekday', models.IntegerField(blank=True, null=True)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('anchor_month', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('until', models.DateField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['due_date', 'category__full_path']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-trn_date']},
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='trn_date',
        ),
    ]
