# Generated by Django 6.0.3 on 2026-09-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_budgetrecurrence_alter_budget_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodSummary',
            fields=[
                ('pk', models.CompositePrimaryKey('period_id', 'category_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=100, unique=True)),
                ('period_label', models.CharField(max_length=100)),
                ('period_end', models.DateField()),
                ('full_path', models.CharField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'budget_periodsummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurrence_type', models.CharField(choices=[('FIXED_TERM', 'Fixed Term'), ('PERPETUAL_FIXED', 'Perpetual Fixed'), ('PERPETUAL_VARIABLE', 'Perpetual Variable')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.category')),
                ('recurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetrecurrence')),
            ],
        ),
    ]
