# Generated by Django 6.0.3 on 2026-09-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_periodsummary_budgetdefinition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetdefinition',
            name='category',
        ),
        migrations.RemoveField(
            model_name='budgetdefinition',
            name='recurrence',
        ),
        migrations.DeleteModel(
            name='BudgetDashboardEntry',
        ),
        migrations.AlterField(
            model_name='budget',
            name='type',
            field=models.CharField(choices=[('P', 'Planned'), ('T', 'Transient')], max_length=20),
        ),
        migrations.DeleteModel(
            name='BudgetDefinition',
        ),
        migrations.DeleteModel(
            name='BudgetRecurrence',
        ),
    ]
