# Generated by Django 6.0.3 on 2026-09-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_remove_budgetdefinition_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='start',
            new_name='start_date',
        ),
    ]
