# Generated by Django 6.0.3 on 2026-09-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_rename_end_period_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='seq',
        ),
    ]
